### ISSUE TITLE
Design Rooms Types

### ISSUE THREAD

**Issue by lhaven** [periodic/GGJ2016#1]
On the video chat, I think we discussed 5 different rooms, with 2-3 prop variations on those rooms. 

Room Type:
- Is a square with 1 to 4 doors
- We'll need 5 or so of these
- Doors should be in the middle of the walls (this is much easier for tech)

This task doesn't seem like that much work, but you might want to define some basic rules for doors.

Note: There is a separate task for variations on these rooms.

**Comment by Plangg** [comment]
5 Basic room layout  https://docs.google.com/spreadsheets/d/1Eg0FSIKY82ByZx9CMnBt-UfvX10dEHk1fSb92lw-W_8/edit#gid=0
