### ISSUE TITLE
Design Room Variations

### ISSUE THREAD

**Issue by lhaven** [periodic/GGJ2016#5]
On the video chat, I think we discussed 5 different rooms, with 2-3 prop variations on those rooms.

Room Variation:
- A variation is a change in configuration of the following elements of a room
- \- Walls
- \- Props (chairs tables, etc.)
- Note: Doors must stay in the same position as the base room type.
- Wee will need 2-3 of

**Comment by Plangg** [comment]
Added some props to the Room Layout spreadsheet.

https://docs.google.com/spreadsheets/d/1Eg0FSIKY82ByZx9CMnBt-UfvX10dEHk1fSb92lw-W_8/edit#gid=0
