### ISSUE TITLE
Create Prop List

### ISSUE THREAD

**Issue by lhaven** [periodic/GGJ2016#6]
Create the a list of props you would like Zoe to make. This might include chairs, desks, barrels, crates chests, couches, bookshelves, rugs, or other ground decorations, etc. You should request # props and order then from most need top to bottom, with the top being needed most. 

The task to create the props can be found here: #7 

Note: I didn't get a chance to ask Zoe how many props she could handle, I imagine 10 would be a reasonable number, but I'm not sure.

**Comment by Plangg** [comment]
Asset list, props are on prop tab 
https://docs.google.com/spreadsheets/d/16Ycc8eExLIptXWU2mU-yVjLQOV3YnT5xlNQW8nVvqNo/edit#gid=814676989
